# Generated by Django 5.1.5 on 2025-02-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_verifed_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refreshtoken',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
