# Generated by Django 5.2 on 2025-07-02 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_refreshtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verifed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_code',
        ),
    ]
